language: android
dist: trusty

android:
  components:
    - tools
    - build-tools-29.0.3
    - android-29
    - extra-android-m2repository

jdk: oraclejdk8

notifications:
  email: false

sudo: false

before_script:
- mkdir "$ANDROID_HOME/licenses" || true
- echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"

cache:
  directories:
    - $HOME/.gradle

script: ./gradlew test
